import os
import sys
import uuid
import json
import subprocess
import shutil
import tempfile
from pathlib import Path
from typing import Dict, Any, Tuple, Optional
from fastapi import UploadFile, HTTPException
# Correct import for the root directory to find dataset_nao
ROOT_DIR = Path(__file__).resolve().parent.parent.parent.parent
IG_DIR = ROOT_DIR / "interaction-grammar"
DATASET_NAO_DIR = IG_DIR / "dataset_nao"
sys.path.append(str(IG_DIR))

try:
    from src.compiler.validator import (
        SchemaValidator,
        SemanticValidator,
        ValidationError,
        prepare_contract_for_validation,
    )
    from src.compiler.parser import ContractParser, ParserError
    from jsonschema import ValidationError as JsonSchemaError
except ImportError as e:
    print(f"Warning: Failed to import interaction-grammar modules: {e}")

from transformer import audit_mapper
from config import get_settings

def get_dataset_root() -> Path:
    settings = get_settings()
    root = Path(settings.dataset_root)
    if not root.is_absolute():
        root = Path(__file__).parent.parent.parent / root
    return root.resolve()

class UploadError(Exception):
    pass

_TEXT_ENCODING = "utf-8-sig"

def _parse_upload_json(content: bytes | str) -> Dict[str, Any]:
    if isinstance(content, bytes):
        text = content.decode(_TEXT_ENCODING)
    else:
        text = content.lstrip("﻿")
    return json.loads(text)

def generate_markdown_report(scenario_id: str, result_dict: dict) -> str:
    """Generates a professional markdown report based on the audit result."""
    verdict = result_dict["verdict"]
    report = f"# Audit Report: {scenario_id}\n\n"
    report += f"**Verdict:** `{'✅ PASS' if verdict == 'PASS' else '❌ FAIL'}`\n\n"

    if verdict != "PASS":
        report += "## Failure Analysis\n"
        report += f"- **Error Code:** `{result_dict.get('error_code', 'Unknown')}`\n"
        report += f"- **Operator:** `{result_dict.get('operator', 'N/A')}`\n"
        report += f"- **Clause Path:** `{result_dict.get('clause_path', '$')}`\n"
        report += f"- **Responsible Agent:** `{result_dict.get('responsible_agent', 'Unknown')}`\n"

        if "budget" in result_dict:
            report += f"- **Budget:** {result_dict['budget']}\n"
        if "observed" in result_dict:
            report += f"- **Observed Value:** {result_dict['observed']}\n"

        report += "\n### Counterexample Evidence\n"
        report += "The following events were captured as witnesses to this failure:\n\n"
        witness = result_dict.get("witness", {})
        if isinstance(witness, dict):
            for k, v in witness.items():
                report += f"- **{k}:** {v}\n"
        else:
            report += f"- {witness}\n"
    else:
        report += "The interaction successfully adhered to all constraints defined in the contract.\n"

    report += "\n---\n*Generated by Interaction Grammar Auditor*"
    return report

def validate_contract_file(contract_file: UploadFile = None, contract_text: str = None) -> Dict[str, Any]:
    try:
        if contract_file:
            contract_data = _parse_upload_json(contract_file.file.read())
        elif contract_text:
            contract_data = _parse_upload_json(contract_text)
        else:
            raise UploadError("No contract file or text provided")

        prepare_contract_for_validation(contract_data)
        schema_path = IG_DIR / "schema" / "schema.json"
        if schema_path.exists():
            schema_validator = SchemaValidator(str(schema_path))
            try:
                schema_validator.validate(contract_data)
            except JsonSchemaError as e:
                raise UploadError(f"Contract Schema Validation Error: {e.message}")

        try:
            parser = ContractParser()
            ast = parser.parse(contract_data)
            semantic_validator = SemanticValidator()
            semantic_validator.validate(ast)
        except (ParserError, ValidationError) as e:
            raise UploadError(f"Contract Semantic Error: [{e.code}] {e.message}")

        return {"status": "success", "message": "Contract is valid!"}
    except UploadError:
        raise
    except Exception as e:
        raise UploadError(str(e))

def handle_upload(
    scenario_id: str,
    contract_file: UploadFile = None,
    contract_text: str = None,
    trace_file: UploadFile = None,
    interaction_type: str = "Turn-taking / acknowledgment",
    robot_platform: str = "NAO",
) -> Dict[str, Any]:
    temp_dir = Path(tempfile.gettempdir()) / f"ig_upload_{uuid.uuid4().hex}"
    temp_dir.mkdir(parents=True, exist_ok=True)

    try:
        contract_path = temp_dir / "contract.ig.json"
        if contract_file:
            with open(contract_path, "wb") as f:
                f.write(contract_file.file.read())
        elif contract_text:
            with open(contract_path, "w", encoding="utf-8") as f:
                f.write(contract_text)
        else:
            raise UploadError("No contract file or text provided")

        original_ext = Path(trace_file.filename).suffix
        trace_path = temp_dir / f"uploaded_trace{original_ext}"
        with open(trace_path, "wb") as f:
            f.write(trace_file.file.read())

        try:
            with open(contract_path, "r", encoding=_TEXT_ENCODING) as f:
                contract_data = json.load(f)
        except json.JSONDecodeError as e:
            raise UploadError(f"Invalid JSON in contract file: {e}")

        prepare_contract_for_validation(contract_data)
        schema_path = IG_DIR / "schema" / "schema.json"
        if schema_path.exists():
            schema_validator = SchemaValidator(str(schema_path))
            try:
                schema_validator.validate(contract_data)
            except JsonSchemaError as e:
                raise UploadError(f"Contract Schema Validation Error: {e.message}")

        try:
            parser = ContractParser()
            ast = parser.parse(contract_data)
            semantic_validator = SemanticValidator()
            semantic_validator.validate(ast)
        except (ParserError, ValidationError) as e:
            raise UploadError(f"Contract Semantic Error: [{e.code}] {e.message}")

        jsonl_trace_path = trace_path
        if original_ext in [".bag", ".db3"]:
            jsonl_trace_path = temp_dir / "trace.jsonl"
            script_path = IG_DIR / "scripts" / "ig_extract_trace.py"
            env = os.environ.copy()
            env["PYTHONPATH"] = str(IG_DIR)
            result = subprocess.run(
                [sys.executable, str(script_path), "--bag", str(trace_path), "--out", str(jsonl_trace_path)],
                capture_output=True,
                encoding="utf-8",
                errors="replace",
                env=env,
            )
            if result.returncode != 0:
                raise UploadError(f"Failed to extract trace from bag: {result.stderr}")
        elif original_ext != ".jsonl":
            raise UploadError(f"Unsupported trace file extension: {original_ext}. Use .jsonl, .bag, or .db3.")

        raw_events = []
        with open(jsonl_trace_path, "r", encoding=_TEXT_ENCODING) as f:
            for line in f:
                if line.strip():
                    raw_events.append(json.loads(line))

        if not raw_events:
            raise UploadError("Trace is empty.")

        audit_script = IG_DIR / "src" / "cli" / "audit.py"
        env = os.environ.copy()
        env["PYTHONPATH"] = str(IG_DIR)
        result = subprocess.run(
            [sys.executable, str(audit_script), "--contract", str(contract_path), "--trace", str(jsonl_trace_path)],
            capture_output=True,
            encoding="utf-8",
            errors="replace",
            env=env,
        )

        try:
            raw_audit = json.loads(result.stdout)
        except json.JSONDecodeError:
            raise UploadError(f"Auditor failed to run. Stderr: {result.stderr}\nStdout: {result.stdout}")

        contract_id_name = contract_file.filename if contract_file else "manual_contract.ig.json"
        scenario_pkg = audit_mapper.transform_scenario(
            scenario_id=scenario_id,
            contract_id=contract_id_name,
            raw_trace_events=raw_events,
            raw_audit=raw_audit,
            interaction_type=interaction_type,
            robot_platform=robot_platform,
            source_bag=trace_file.filename if original_ext in [".bag", ".db3"] else None,
        )

        # PRD EXPORT LOGIC
        prd_scenario_dir = DATASET_NAO_DIR / scenario_id
        if prd_scenario_dir.exists():
            # Use the Flat PRD structure
            with open(prd_scenario_dir / "trace.jsonl", "w", encoding="utf-8") as f:
                for event in raw_events:
                    f.write(json.dumps(event) + "\n")

            with open(prd_scenario_dir / "contract.ig.json", "w", encoding="utf-8") as f:
                json.dump(contract_data, f, indent=2, ensure_ascii=False)

            with open(prd_scenario_dir / "audit_report.json", "w", encoding="utf-8") as f:
                json.dump(scenario_pkg["audit_report.json"], f, indent=2, ensure_ascii=False)

            if scenario_pkg["counterexample.json"]:
                with open(prd_scenario_dir / "counterexample.json", "w", encoding="utf-8") as f:
                    json.dump(scenario_pkg["counterexample.json"], f, indent=2, ensure_ascii=False)

            md_report = generate_markdown_report(scenario_id, raw_audit)
            with open(prd_scenario_dir / "report.md", "w", encoding="utf-8") as f:
                f.write(md_report)

            # Update metadata.yaml if it exists
            meta_path = prd_scenario_dir / "metadata.yaml"
            if meta_path.exists():
                # Simple append or update of audit results
                with open(meta_path, "r", encoding="utf-8") as f:
                    lines = f.read().splitlines()

                # Update verdict in metadata
                new_lines = []
                updated = False
                for line in lines:
                    if line.startswith("expected_verdict:"):
                        new_lines.append(f"actual_verdict: {raw_audit['verdict']}")
                        updated = True
                    else:
                        new_lines.append(line)
                if not updated:
                    new_lines.append(f"actual_verdict: {raw_audit['verdict']}")

                with open(meta_path, "w", encoding="utf-8") as f:
                    f.write("\n".join(new_lines) + "\n")

        # Keep existing legacy dataset save as well for backward compatibility
        target_dir = get_dataset_root() / scenario_id
        if target_dir.exists():
            shutil.rmtree(target_dir)

        (target_dir / "traces").mkdir(parents=True)
        (target_dir / "contracts").mkdir(parents=True)
        (target_dir / "audits").mkdir(parents=True)

        with open(target_dir / "metadata.yaml", "w", encoding="utf-8") as f:
            f.write(scenario_pkg["metadata.yaml"])

        with open(target_dir / "contracts" / "contract.ig.json", "w", encoding="utf-8") as f:
            json.dump(contract_data, f, indent=2, ensure_ascii=False)

        with open(target_dir / "traces" / "trace.json", "w", encoding="utf-8") as f:
            json.dump(scenario_pkg["trace.json"], f, indent=2, ensure_ascii=False)

        with open(target_dir / "audits" / "audit_report.json", "w", encoding="utf-8") as f:
            json.dump(scenario_pkg["audit_report.json"], f, indent=2, ensure_ascii=False)

        if scenario_pkg["counterexample.json"]:
            with open(target_dir / "audits" / "counterexample.json", "w", encoding="utf-8") as f:
                json.dump(scenario_pkg["counterexample.json"], f, indent=2, ensure_ascii=False)

        return {"scenario_id": scenario_id, "status": "success"}

    finally:
        shutil.rmtree(temp_dir, ignore_errors=True)
