import json
import sys
from pathlib import Path
from typing import Any

# Ensure the src directory is in the path for imports
import os
ROOT_DIR = Path(__file__).resolve().parent.parent
sys.path.insert(0, str(ROOT_DIR))

from src.compiler.parser import ContractParser
from src.compiler.validator import prepare_contract_for_validation
from src.audit.trace import Trace, TraceError
from src.audit.auditor import Auditor, AuditVerdict

DATASET_NAO_DIR = ROOT_DIR / "dataset_nao"
MATRIX_FILE = DATASET_NAO_DIR / "scenario_matrix.json"

def generate_markdown_report(scenario_id: str, result_dict: dict) -> str:
    """Generates a professional markdown report based on the audit result."""
    verdict = result_dict["verdict"]

    report = f"# Audit Report: {scenario_id}\n\n"
    report += f"**Verdict:** `{'✅ PASS' if verdict == 'PASS' else '❌ FAIL'}`\n\n"

    if verdict == "FAIL":
        report += "## Failure Analysis\n"
        report += f"- **Error Code:** `{result_dict.get('error_code', 'Unknown')}`\n"
        report += f"- **Operator:** `{result_dict.get('operator', 'N/A')}`\n"
        report += f"- **Clause Path:** `{result_dict.get('clause_path', '$')}`\n"
        report += f"- **Responsible Agent:** `{result_dict.get('responsible_agent', 'Unknown')}`\n"

        if "budget" in result_dict:
            report += f"- **Budget:** {result_dict['budget']}\n"
        if "observed" in result_dict:
            report += f"- **Observed Value:** {result_dict['observed']}\n"

        report += "\n### Counterexample Evidence\n"
        report += "The following events were captured as witnesses to this failure:\n\n"
        witness = result_dict.get("witness", {})
        if isinstance(witness, dict):
            for k, v in witness.items():
                report += f"- **{k}:** {v}\n"
        else:
            report += f"- {witness}\n"
    else:
        report += "The interaction successfully adhered to all constraints defined in the contract.\n"

    report += "\n---\n*Generated by Interaction Grammar Auditor*"
    return report

def run_scenario_audit(scenario_id: str):
    print(f"Auditing {scenario_id}...", end=" ")

    scenario_dir = DATASET_NAO_DIR / scenario_id
    contract_path = scenario_dir / "contract.ig.json"
    trace_path = scenario_dir / "trace.jsonl"

    if not contract_path.exists() or not trace_path.exists():
        print(f"Skipped (Missing contract or trace in {scenario_id})")
        return

    try:
        # 1. Load Contract
        with open(contract_path, 'r', encoding='utf-8-sig') as f:
            contract_data = json.load(f)
        prepare_contract_for_validation(contract_data)
        ast = ContractParser().parse(contract_data)

        # 2. Load Trace
        trace = Trace.from_file(str(trace_path))

        # 3. Audit
        result = Auditor(ast).audit(trace)
        result_dict = result.to_dict()

        # 4. Save Results
        # Audit Report
        with open(scenario_dir / "audit_report.json", "w", encoding="utf-8") as f:
            json.dump(result_dict, f, indent=2)

        # Report JSON
        with open(scenario_dir / "report.json", "w", encoding="utf-8") as f:
            json.dump(result_dict, f, indent=2)

        # Counterexample (only if FAIL)
        if result.verdict == AuditVerdict.FAIL:
            with open(scenario_dir / "counterexample.json", "w", encoding="utf-8") as f:
                json.dump(result_dict, f, indent=2)

        # Markdown Report
        md_report = generate_markdown_report(scenario_id, result_dict)
        with open(scenario_dir / "report.md", "w", encoding="utf-8") as f:
            f.write(md_report)

        print(f"SUCCESS {result.verdict}")

    except Exception as e:
        print(f"ERROR: {e}")

def main():
    if not MATRIX_FILE.exists():
        print(f"Error: scenario_matrix.json not found at {MATRIX_FILE}")
        sys.exit(1)

    with open(MATRIX_FILE, "r", encoding="utf-8") as f:
        matrix = json.load(f)

    scenario_ids = [s["scenario_id"] for s in matrix]

    print(f"Starting batch audit for {len(scenario_ids)} scenarios...\n")
    for sid in scenario_ids:
        run_scenario_audit(sid)
    print("\nBatch audit complete.")

if __name__ == "__main__":
    main()
